name = "pineapplegallery"
compatibility_date = "2024-11-27"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]


[[r2_buckets]]
binding = "R2"
bucket_name = "pineapplegallery-bucket"

[[d1_databases]]
binding = "DB"
database_name = "pineapplegallery-database"
database_id = "1c365a6b-0608-4d74-a5c0-6ecfdf9a55e4"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "0731a49b8c1042d199e125d6ceff50a5"

#----------------------------------------------------------- CONFIG

[vars]

# Page title
PAGE_TITLE = "Lauren & Daniel | Wedding Gallery"

# Page description
DESCRIPTION = "Wedding photo gallery for Lauren Cheveralls & Daniel Welch celebration on 31 August 2027"

# Copyright attribution name
COPYRIGHT = "Lauren Cheveralls & Daniel Welch"

# Image transformations
IMGT = "true"

# Use Cache KV functionality
USE_CACHE = "true"

# "Admin Panel Credentials – remove the comment to set them here, or keep it commented to manage them via the CF Dashboard.
# USERNAME = "admin"
# PASSWORD = "superSecretPassword"

# Path to the gallery application (should contain no slashes, unless this serves on root, which then it should be a single slash)
# Make sure to also update index.jsx accordingly.
GALLERY_PATH = "/"

# Color scheme used for CSS
# Valid color names can be found here: https://picocss.com/docs/colors
COLOR_SCHEME = "amber"
